### ISSUE TITLE
doctests failing due to using SAGE_TMP which is now gone

### ISSUE THREAD

**Issue by seblabbe** [mkoeppe/sage-numerical-backends-coin#8]
Using:
```
$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.2.beta1, Release Date: 2023-09-01              │
│ Using Python 3.11.1. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
```
The command `sage -i -c sage_numerical_backends_coin` as suggested in https://doc.sagemath.org/html/en/thematic_tutorials/linear_programming.html returns some doctests failing due to SAGE_TMP gone:

```
[sage_numerical_backends_coin-9.0b12] Doctesting 3 files.
[sage_numerical_backends_coin-9.0b12] sage -t --random-seed=91966486381968181557026538906550506482 sage_numerical_backends_coin/coin_backend.pxd
[sage_numerical_backends_coin-9.0b12]     [0 tests, 0.00 s]
[sage_numerical_backends_coin-9.0b12] sage -t --random-seed=91966486381968181557026538906550506482 sage_numerical_backends_coin/coin_backend.pyx
[sage_numerical_backends_coin-9.0b12] **********************************************************************
[sage_numerical_backends_coin-9.0b12] File "sage_numerical_backends_coin/coin_backend.pyx", line 1157, in sage_numerical_backends_coin.coin_backend.CoinBackend.HAVE_SAGE_CPYTHON_STRING.write_mps
[sage_numerical_backends_coin-9.0b12] Failed example:
[sage_numerical_backends_coin-9.0b12]     p.write_mps(os.path.join(SAGE_TMP, "lp_problem.mps"), 0)
[sage_numerical_backends_coin-9.0b12] Exception raised:
[sage_numerical_backends_coin-9.0b12]     Traceback (most recent call last):
[sage_numerical_backends_coin-9.0b12]       File "/home/slabbe/GitBox/sage/src/sage/doctest/forker.py", line 709, in _run
[sage_numerical_backends_coin-9.0b12]         self.compile_and_execute(example, compiler, test.globs)
[sage_numerical_backends_coin-9.0b12]       File "/home/slabbe/GitBox/sage/src/sage/doctest/forker.py", line 1144, in compile_and_execute
[sage_numerical_backends_coin-9.0b12]         exec(compiled, globs)
[sage_numerical_backends_coin-9.0b12]       File "<doctest sage_numerical_backends_coin.coin_backend.CoinBackend.HAVE_SAGE_CPYTHON_STRING.write_mps[5]>", line 1, in <module>
[sage_numerical_backends_coin-9.0b12]         p.write_mps(os.path.join(SAGE_TMP, "lp_problem.mps"), Integer(0))
[sage_numerical_backends_coin-9.0b12]                                  ^^^^^^^^
[sage_numerical_backends_coin-9.0b12]     NameError: name 'SAGE_TMP' is not defined
[sage_numerical_backends_coin-9.0b12] **********************************************************************
[sage_numerical_backends_coin-9.0b12] File "sage_numerical_backends_coin/coin_backend.pyx", line 1180, in sage_numerical_backends_coin.coin_backend.CoinBackend.HAVE_SAGE_CPYTHON_STRING.write_lp
[sage_numerical_backends_coin-9.0b12] Failed example:
[sage_numerical_backends_coin-9.0b12]     p.write_lp(os.path.join(SAGE_TMP, "lp_problem.lp"))
[sage_numerical_backends_coin-9.0b12] Exception raised:
[sage_numerical_backends_coin-9.0b12]     Traceback (most recent call last):
[sage_numerical_backends_coin-9.0b12]       File "/home/slabbe/GitBox/sage/src/sage/doctest/forker.py", line 709, in _run
[sage_numerical_backends_coin-9.0b12]         self.compile_and_execute(example, compiler, test.globs)
[sage_numerical_backends_coin-9.0b12]       File "/home/slabbe/GitBox/sage/src/sage/doctest/forker.py", line 1144, in compile_and_execute
[sage_numerical_backends_coin-9.0b12]         exec(compiled, globs)
[sage_numerical_backends_coin-9.0b12]       File "<doctest sage_numerical_backends_coin.coin_backend.CoinBackend.HAVE_SAGE_CPYTHON_STRING.write_lp[5]>", line 1, in <module>
[sage_numerical_backends_coin-9.0b12]         p.write_lp(os.path.join(SAGE_TMP, "lp_problem.lp"))
[sage_numerical_backends_coin-9.0b12]                                 ^^^^^^^^
[sage_numerical_backends_coin-9.0b12]     NameError: name 'SAGE_TMP' is not defined
[sage_numerical_backends_coin-9.0b12] **********************************************************************
[sage_numerical_backends_coin-9.0b12] File "sage_numerical_backends_coin/coin_backend.pyx", line 1203, in sage_numerical_backends_coin.coin_backend.CoinBackend.ELSE.write_mps
[sage_numerical_backends_coin-9.0b12] Failed example:
[sage_numerical_backends_coin-9.0b12]     p.write_mps(os.path.join(SAGE_TMP, "lp_problem.mps"), 0)
[sage_numerical_backends_coin-9.0b12] Exception raised:
[sage_numerical_backends_coin-9.0b12]     Traceback (most recent call last):
[sage_numerical_backends_coin-9.0b12]       File "/home/slabbe/GitBox/sage/src/sage/doctest/forker.py", line 709, in _run
[sage_numerical_backends_coin-9.0b12]         self.compile_and_execute(example, compiler, test.globs)
[sage_numerical_backends_coin-9.0b12]       File "/home/slabbe/GitBox/sage/src/sage/doctest/forker.py", line 1144, in compile_and_execute
[sage_numerical_backends_coin-9.0b12]         exec(compiled, globs)
[sage_numerical_backends_coin-9.0b12]       File "<doctest sage_numerical_backends_coin.coin_backend.CoinBackend.ELSE.write_mps[5]>", line 1, in <module>
[sage_numerical_backends_coin-9.0b12]         p.write_mps(os.path.join(SAGE_TMP, "lp_problem.mps"), Integer(0))
[sage_numerical_backends_coin-9.0b12]                                  ^^^^^^^^
[sage_numerical_backends_coin-9.0b12]     NameError: name 'SAGE_TMP' is not defined
[sage_numerical_backends_coin-9.0b12] **********************************************************************
[sage_numerical_backends_coin-9.0b12] File "sage_numerical_backends_coin/coin_backend.pyx", line 1225, in sage_numerical_backends_coin.coin_backend.CoinBackend.ELSE.write_lp
[sage_numerical_backends_coin-9.0b12] Failed example:
[sage_numerical_backends_coin-9.0b12]     p.write_lp(os.path.join(SAGE_TMP, "lp_problem.lp"))
[sage_numerical_backends_coin-9.0b12] Exception raised:
[sage_numerical_backends_coin-9.0b12]     Traceback (most recent call last):
[sage_numerical_backends_coin-9.0b12]       File "/home/slabbe/GitBox/sage/src/sage/doctest/forker.py", line 709, in _run
[sage_numerical_backends_coin-9.0b12]         self.compile_and_execute(example, compiler, test.globs)
[sage_numerical_backends_coin-9.0b12]       File "/home/slabbe/GitBox/sage/src/sage/doctest/forker.py", line 1144, in compile_and_execute
[sage_numerical_backends_coin-9.0b12]         exec(compiled, globs)
[sage_numerical_backends_coin-9.0b12]       File "<doctest sage_numerical_backends_coin.coin_backend.CoinBackend.ELSE.write_lp[5]>", line 1, in <module>
[sage_numerical_backends_coin-9.0b12]         p.write_lp(os.path.join(SAGE_TMP, "lp_problem.lp"))
[sage_numerical_backends_coin-9.0b12]                                 ^^^^^^^^
[sage_numerical_backends_coin-9.0b12]     NameError: name 'SAGE_TMP' is not defined
[sage_numerical_backends_coin-9.0b12] **********************************************************************
[sage_numerical_backends_coin-9.0b12] 4 items had failures:
[sage_numerical_backends_coin-9.0b12]    1 of   7 in sage_numerical_backends_coin.coin_backend.CoinBackend.ELSE.write_lp
[sage_numerical_backends_coin-9.0b12]    1 of   7 in sage_numerical_backends_coin.coin_backend.CoinBackend.ELSE.write_mps
[sage_numerical_backends_coin-9.0b12]    1 of   7 in sage_numerical_backends_coin.coin_backend.CoinBackend.HAVE_SAGE_CPYTHON_STRING.write_lp
[sage_numerical_backends_coin-9.0b12]    1 of   7 in sage_numerical_backends_coin.coin_backend.CoinBackend.HAVE_SAGE_CPYTHON_STRING.write_mps
[sage_numerical_backends_coin-9.0b12]     [367 tests, 4 failures, 0.23 s]
[sage_numerical_backends_coin-9.0b12] sage -t --random-seed=91966486381968181557026538906550506482 sage_numerical_backends_coin/__init__.py
[sage_numerical_backends_coin-9.0b12]     [0 tests, 0.00 s]
[sage_numerical_backends_coin-9.0b12] ----------------------------------------------------------------------
[sage_numerical_backends_coin-9.0b12] sage -t --random-seed=91966486381968181557026538906550506482 sage_numerical_backends_coin/coin_backend.pyx  # 4 doctests failed
[sage_numerical_backends_coin-9.0b12] ----------------------------------------------------------------------
[sage_numerical_backends_coin-9.0b12] Total time for all tests: 0.4 seconds
[sage_numerical_backends_coin-9.0b12]     cpu time: 0.2 seconds
[sage_numerical_backends_coin-9.0b12]     cumulative wall time: 0.2 seconds
[sage_numerical_backends_coin-9.0b12] Features detected for doctesting: 
[sage_numerical_backends_coin-9.0b12] pytest is not installed in the venv, skip checking tests that rely on it
[sage_numerical_backends_coin-9.0b12] 
[sage_numerical_backends_coin-9.0b12] real	0m10.894s
[sage_numerical_backends_coin-9.0b12] user	0m10.629s
[sage_numerical_backends_coin-9.0b12] sys	0m0.683s
[sage_numerical_backends_coin-9.0b12] ************************************************************************
[sage_numerical_backends_coin-9.0b12] Error testing package sage_numerical_backends_coin-9.0b12
[sage_numerical_backends_coin-9.0b12] ************************************************************************
```

**Comment by dimpase** [comment]
fixed by the latest commit 883ffd0d395b263d1f5d886fd4f7d203782883f4
